version: '3'
services:
  mongo:
    build: ./docker-dbmongo/
    ports:
    - "27018:27017"
  apirest0:
    build: ./apirest0/
    links:
    - mongo
    ports:
    - "8001:8001"
  apirest1:
    build: ./apirest1/
    links:
    - apirest0
    ports:
    - "8002:8002"
