version: '3'
services:
  mongo:
    build: ./dbMongo/
    ports:
    - "27018:27017"
  apirest0:
    build: ./apiRest0/
    links:
    - mongo
    ports:
    - "8001:8001"
  apirest1:
    build: ./apiRest1/
    links:
    - apirest0
    ports:
    - "8002:8002"
